let
    Source = #"Index Price",

    #"Promote Headers" =
        Table.PromoteHeaders(
            Source,
            [PromoteAllScalars = true]
        ),

    #"Clean Column Names" =
        Table.TransformColumnNames(
            #"Promote Headers",
            each Text.Trim(Text.Clean(Text.From(_)))
        ),

    #"Changed Date Type" =
        Table.TransformColumns(
            #"Clean Column Names",
            {
                {
                    "Date",
                    each Date.From(_),
                    type date
                }
            }
        ),

    #"Unpivot Index Columns" =
        Table.UnpivotOtherColumns(
            #"Changed Date Type",
            {"Date"},
            "IndexCode",
            "Price"
        ),

    #"Changed Types" =
        Table.TransformColumnTypes(
            #"Unpivot Index Columns",
            {
                {"IndexCode", type text},
                {"Price", type number}
            }
        ),

    #"Added Index Name" =
        Table.AddColumn(
            #"Changed Types",
            "IndexName",
            each [IndexCode],
            type text
        ),

    #"Reordered Columns" =
        Table.SelectColumns(
            #"Added Index Name",
            {
                "IndexName",
                "IndexCode",
                "Date",
                "Price"
            }
        )
in
    #"Reordered Columns"
