let
    ProductMasterSource = #"Product Master",
    CohortSource = #"Cohort Schedule",
    IndexSource = #"Index Price",
    FXSource = #"FX Rate",

    CleanColumnName = (name as text) as text =>
        Text.Upper(
            Text.Remove(
                Text.Trim(Text.From(name)),
                {" ", ".", "_", "-", "(", ")", "/", "#", ":", "'", """", Character.FromNumber(160)}
            )
        ),

    CleanText = (value as any) as nullable text =>
        if value = null then null else Text.Trim(Text.From(value)),

    CleanIndexCode = (value as any) as nullable text =>
        let
            cleaned = if value = null then null else CleanColumnName(Text.From(value)),
            withoutIndex = if cleaned <> null and Text.EndsWith(cleaned, "INDEX")
                then Text.Start(cleaned, Text.Length(cleaned) - 5)
                else cleaned
        in
            withoutIndex,

    ToNumber = (value as any) as nullable number =>
        let
            t = if value = null then null else Text.Trim(Text.From(value)),
            removed = if t = null then null else Text.Replace(Text.Replace(Text.Replace(t, "%", ""), ",", ""), "~", ""),
            n = try Number.From(value) otherwise try Number.FromText(removed) otherwise null
        in
            n,

    ToRate = (value as any) as nullable number =>
        let
            n = ToNumber(value)
        in
            if n = null then null else if n > 1 then n / 100 else n,

    ToDate = (value as any) as nullable date =>
        try Date.From(value)
        otherwise try Date.FromText(Text.From(value), "en-GB")
        otherwise try Date.FromText(Text.From(value), "en-US")
        otherwise null,

    AddMissingColumns = (tbl as table, required as list) as table =>
        List.Accumulate(
            required,
            tbl,
            (state as table, col as text) =>
                if Table.HasColumns(state, col) then state else Table.AddColumn(state, col, each null)
        ),

    ProductMasterNormalized = Table.TransformColumnNames(ProductMasterSource, each CleanColumnName(_)),
    ProductMasterColumns = AddMissingColumns(
        ProductMasterNormalized,
        {"COMPANY", "COMPANYNAME", "PRODUCTNAME", "INDEX", "INDEXCODE", "PR", "FORMULA"}
    ),

    ProductMaster = Table.TransformColumnTypes(
        Table.TransformColumns(
            ProductMasterColumns,
            {
                {"COMPANY", each CleanText(_), type text},
                {"COMPANYNAME", each CleanText(_), type text},
                {"PRODUCTNAME", each CleanText(_), type text},
                {"INDEX", each CleanText(_), type text},
                {"INDEXCODE", each CleanIndexCode(_), type text},
                {"PR", each ToRate(_), type number},
                {"FORMULA", each if _ = null or Text.Trim(Text.From(_)) = "" then "PR" else Text.Upper(Text.Replace(Text.Trim(Text.From(_)), " ", "_")), type text}
            }
        ),
        {
            {"COMPANY", type text},
            {"COMPANYNAME", type text},
            {"PRODUCTNAME", type text},
            {"INDEX", type text},
            {"INDEXCODE", type text},
            {"PR", type number},
            {"FORMULA", type text}
        }
    ),

    ProductMasterFinal = Table.AddColumn(
        Table.AddColumn(
            Table.AddColumn(
                ProductMaster,
                "CompanyFinal",
                each
                    if [COMPANY] <> null and [COMPANY] <> "" then [COMPANY]
                    else if [COMPANYNAME] <> null and [COMPANYNAME] <> "" then [COMPANYNAME]
                    else "MTL",
                type text
            ),
            "FormulaType",
            each [FORMULA],
            type text
        ),
        "Volatility",
        each null,
        type number
    ),

    CohortNormalized = Table.TransformColumnNames(CohortSource, each CleanColumnName(_)),
    CohortColumns = AddMissingColumns(
        CohortNormalized,
        {"PRODUCTNAME", "COHORTNO", "COHORTDURATION", "COHORTSTARTDATE", "COHORTENDDATE"}
    ),

    CohortSchedule = Table.TransformColumnTypes(
        Table.TransformColumns(
            CohortColumns,
            {
                {"PRODUCTNAME", each CleanText(_), type text},
                {"COHORTNO", each ToNumber(_), Int64.Type},
                {"COHORTDURATION", each ToNumber(_), type number},
                {"COHORTSTARTDATE", each ToDate(_), type date},
                {"COHORTENDDATE", each ToDate(_), type date}
            }
        ),
        {
            {"PRODUCTNAME", type text},
            {"COHORTNO", Int64.Type},
            {"COHORTDURATION", type number},
            {"COHORTSTARTDATE", type date},
            {"COHORTENDDATE", type date}
        }
    ),

    IndexNormalized = Table.TransformColumnNames(IndexSource, each CleanColumnName(_)),
    IndexWithDate = AddMissingColumns(IndexNormalized, {"DATE"}),
    IndexTyped = Table.TransformColumns(IndexWithDate, {{"DATE", each ToDate(_), type date}}),

    IndexPriceLong = Table.UnpivotOtherColumns(
        IndexTyped,
        {"DATE"},
        "IndexCode",
        "Price"
    ),

    IndexPriceTyped = Table.TransformColumnTypes(
        Table.TransformColumns(
            IndexPriceLong,
            {
                {"IndexCode", each CleanIndexCode(_), type text},
                {"Price", each ToNumber(_), type number}
            }
        ),
        {
            {"IndexCode", type text},
            {"Price", type number}
        }
    ),

    FXNormalized = Table.TransformColumnNames(FXSource, each CleanColumnName(_)),
    FXColumns = AddMissingColumns(FXNormalized, {"DATE", "MONTH", "เดือน", "USDTHB", "USDTH"}),

    FXDateColumn =
        if Table.HasColumns(FXColumns, "DATE") and List.NonNullCount(FXColumns[DATE]) > 0 then "DATE"
        else if Table.HasColumns(FXColumns, "MONTH") and List.NonNullCount(FXColumns[MONTH]) > 0 then "MONTH"
        else if Table.HasColumns(FXColumns, "เดือน") then "เดือน"
        else "DATE",

    FXRateColumn =
        if Table.HasColumns(FXColumns, "USDTHB") and List.NonNullCount(FXColumns[USDTHB]) > 0 then "USDTHB"
        else if Table.HasColumns(FXColumns, "USDTH") and List.NonNullCount(FXColumns[USDTH]) > 0 then "USDTH"
        else "USDTHB",

    FXSelected = Table.SelectColumns(FXColumns, {FXDateColumn, FXRateColumn}, MissingField.UseNull),
    FXRenamed = Table.RenameColumns(
        FXSelected,
        {
            {FXDateColumn, "Date"},
            {FXRateColumn, "FXRate"}
        },
        MissingField.Ignore
    ),

    FXTyped = Table.TransformColumnTypes(
        Table.TransformColumns(
            FXRenamed,
            {
                {"Date", each ToDate(_), type date},
                {"FXRate", each ToNumber(_), type number}
            }
        ),
        {
            {"Date", type date},
            {"FXRate", type number}
        }
    ),

    FXWithPair = Table.AddColumn(
        FXTyped,
        "FXPair",
        each "USD/THB",
        type text
    ),

    MergeProduct = Table.NestedJoin(
        CohortSchedule,
        {"PRODUCTNAME"},
        ProductMasterFinal,
        {"PRODUCTNAME"},
        "Product",
        JoinKind.LeftOuter
    ),

    ExpandProduct = Table.ExpandTableColumn(
        MergeProduct,
        "Product",
        {
            "CompanyFinal",
            "INDEX",
            "INDEXCODE",
            "PR",
            "FormulaType",
            "Volatility"
        },
        {
            "Company",
            "IndexName",
            "IndexCode",
            "PR",
            "FormulaType",
            "Volatility"
        }
    ),

    MergeIndex = Table.NestedJoin(
        ExpandProduct,
        {"IndexCode"},
        IndexPriceTyped,
        {"IndexCode"},
        "IndexPrice",
        JoinKind.LeftOuter
    ),

    ExpandIndex = Table.ExpandTableColumn(
        MergeIndex,
        "IndexPrice",
        {"DATE", "Price"},
        {"Date", "Price"}
    ),

    FilterAfterStart = Table.SelectRows(
        ExpandIndex,
        each [Date] <> null and [COHORTSTARTDATE] <> null and [Date] >= [COHORTSTARTDATE]
    ),

    AddObservationEndDate = Table.AddColumn(
        FilterAfterStart,
        "ObservationEndDate",
        each [COHORTENDDATE],
        type date
    ),

    FilterBeforeObservationEnd = Table.SelectRows(
        AddObservationEndDate,
        each [ObservationEndDate] = null or [Date] <= [ObservationEndDate]
    ),

    BaseValues = Table.Group(
        FilterBeforeObservationEnd,
        {"PRODUCTNAME", "COHORTNO"},
        {{"CalculatedIndexBaseValue", each try Table.Sort(_, {{"Date", Order.Ascending}}){0}[Price] otherwise null, type number}}
    ),

    MergeBase = Table.NestedJoin(
        FilterBeforeObservationEnd,
        {"PRODUCTNAME", "COHORTNO"},
        BaseValues,
        {"PRODUCTNAME", "COHORTNO"},
        "Base",
        JoinKind.LeftOuter
    ),

    ExpandBase = Table.ExpandTableColumn(
        MergeBase,
        "Base",
        {"CalculatedIndexBaseValue"},
        {"CalculatedIndexBaseValue"}
    ),

    AddIndexBaseValueFinal = Table.AddColumn(
        ExpandBase,
        "IndexBaseValueFinal",
        each [CalculatedIndexBaseValue],
        type number
    ),

    MergeFX = Table.NestedJoin(
        AddIndexBaseValueFinal,
        {"Date"},
        FXWithPair,
        {"Date"},
        "FX",
        JoinKind.LeftOuter
    ),

    ExpandFX = Table.ExpandTableColumn(
        MergeFX,
        "FX",
        {"FXPair", "FXRate"},
        {"FXPair", "FXRate"}
    ),

    RenameColumns = Table.RenameColumns(
        ExpandFX,
        {
            {"PRODUCTNAME", "ProductName"},
            {"COHORTNO", "CohortNo"},
            {"COHORTDURATION", "CohortDuration"},
            {"COHORTSTARTDATE", "CohortStartDate"},
            {"COHORTENDDATE", "CohortEndDate"},
            {"IndexBaseValueFinal", "IndexBaseValue"}
        },
        MissingField.Ignore
    ),

    WithCompanyName = Table.AddColumn(
        RenameColumns,
        "CompanyName",
        each [Company],
        type text
    ),

    FinalColumns = Table.SelectColumns(
        WithCompanyName,
        {
            "Company",
            "CompanyName",
            "ProductName",
            "IndexName",
            "IndexCode",
            "PR",
            "FormulaType",
            "Volatility",
            "CohortNo",
            "CohortDuration",
            "CohortStartDate",
            "CohortEndDate",
            "ObservationEndDate",
            "IndexBaseValue",
            "Date",
            "Price",
            "FXPair",
            "FXRate"
        },
        MissingField.UseNull
    )
in
    FinalColumns
