let
    ProductMasterSource = #"Product Master",
    CohortSource = #"Cohort Schedule",
    IndexSource = #"Index Price",

    CleanColumnName = (name as text) as text =>
        Text.Upper(
            Text.Remove(
                Text.Trim(Text.From(name)),
                {" ", ".", "_", "-", "(", ")", "/", "\", "#", ":", "'", """", Character.FromNumber(160)}
            )
        ),

    CleanIndexCode = (value as any) as nullable text =>
        let
            cleaned = if value = null then null else CleanColumnName(Text.From(value)),
            withoutIndex = if cleaned <> null and Text.EndsWith(cleaned, "INDEX") then Text.Start(cleaned, Text.Length(cleaned) - 5) else cleaned
        in
            withoutIndex,

    ProductMaster = Table.TransformColumnNames(ProductMasterSource, each CleanColumnName(_)),
    ProductCodes =
        Table.Distinct(
            Table.TransformColumns(
                Table.SelectColumns(ProductMaster, {"PRODUCTNAME", "INDEXCODE"}),
                {
                    {"PRODUCTNAME", each Text.From(_), type text},
                    {"INDEXCODE", each CleanIndexCode(_), type text}
                }
            )
        ),

    IndexTable = Table.TransformColumnNames(IndexSource, each CleanColumnName(_)),
    IndexHeaders = List.RemoveItems(Table.ColumnNames(IndexTable), {"DATE"}),
    IndexCodes = Table.FromList(IndexHeaders, Splitter.SplitByNothing(), {"INDEXCODE"}),
    IndexCodesClean = Table.TransformColumns(IndexCodes, {{"INDEXCODE", each CleanIndexCode(_), type text}}),

    Check = Table.NestedJoin(
        ProductCodes,
        {"INDEXCODE"},
        IndexCodesClean,
        {"INDEXCODE"},
        "Matched",
        JoinKind.LeftOuter
    ),

    Result = Table.AddColumn(
        Check,
        "MatchStatus",
        each if Table.RowCount([Matched]) > 0 then "MATCH" else "NO MATCH",
        type text
    ),

    Final = Table.RemoveColumns(Result, {"Matched"})
in
    Final
