
FixDate = (v as any) as nullable date =>
    if v is date then v
    else if v is datetime then Date.From(v)
    else if v is number then Date.AddDays(#date(1899, 12, 30), Number.RoundDown(v))
    else
        try Date.FromText(Text.From(v), "th-TH")
        otherwise try Date.FromText(Text.From(v), "en-GB")
        otherwise try Date.FromText(Text.From(v), "en-CA")
        otherwise null,

#"Fixed Date Columns" =
    Table.TransformColumns(
        #"Previous Step",
        {
            {"Date", each FixDate(_), type date},
            {"CohortStartDate", each FixDate(_), type date},
            {"CohortEndDate", each FixDate(_), type date}
        }
    )
