let
    Source = #"Index Price",
    PromotedHeaders =
        if List.Contains(Table.ColumnNames(Source), "Date")
        then Source
        else Table.PromoteHeaders(Source, [PromoteAllScalars = true]),

    FixDate = (v as any) as nullable date =>
        if v is date then v
        else if v is datetime then Date.From(v)
        else if v is number then Date.AddDays(#date(1899, 12, 30), Number.RoundDown(v))
        else
            let
                t = Text.Trim(Text.From(v)),
                iso = try Date.FromText(t, "en-CA") otherwise null,
                gb = try Date.FromText(t, "en-GB") otherwise null
            in
                if iso <> null then iso else gb,

    TypedDate = Table.TransformColumns(
        PromotedHeaders,
        {{"Date", each FixDate(_), type date}},
        null,
        MissingField.Ignore
    ),

    Long = Table.UnpivotOtherColumns(
        TypedDate,
        {"Date"},
        "IndexCode",
        "Price"
    ),

    Typed = Table.TransformColumnTypes(
        Long,
        {
            {"IndexCode", type text},
            {"Price", type number}
        }
    ),

    AddIndexName = Table.AddColumn(
        Typed,
        "IndexName",
        each [IndexCode],
        type text
    ),

    Final = Table.SelectRows(
        AddIndexName,
        each [Date] <> null and [Price] <> null
    )
in
    Final
