#"Fixed Thai Date" =
    Table.TransformColumns(
        #"Previous Step",
        {
            {
                "Date",
                each
                    let
                        t = Text.Trim(Text.From(_)),
                        cleaned =
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(t,
                                "ม.ค.", "01"),
                                "ก.พ.", "02"),
                                "มี.ค.", "03"),
                                "เม.ย.", "04"),
                                "พ.ค.", "05"),
                                "มิ.ย.", "06"),
                                "ก.ค.", "07"),
                                "ส.ค.", "08"),
                                "ก.ย.", "09"),
                                "ต.ค.", "10"),
                                "พ.ย.", "11"),
                                "ธ.ค.", "12"),
                        parts = Text.Split(cleaned, "-"),
                        result = #date(Number.FromText(parts{2}), Number.FromText(parts{1}), Number.FromText(parts{0}))
                    in
                        result,
                type date
            }
        }
    )#"Fixed Thai Date" =
    Table.TransformColumns(
        #"Previous Step",
        {
            {
                "Date",
                each
                    let
                        t = Text.Trim(Text.From(_)),
                        cleaned =
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(
                            Text.Replace(t,
                                "ม.ค.", "01"),
                                "ก.พ.", "02"),
                                "มี.ค.", "03"),
                                "เม.ย.", "04"),
                                "พ.ค.", "05"),
                                "มิ.ย.", "06"),
                                "ก.ค.", "07"),
                                "ส.ค.", "08"),
                                "ก.ย.", "09"),
                                "ต.ค.", "10"),
                                "พ.ย.", "11"),
                                "ธ.ค.", "12"),
                        parts = Text.Split(cleaned, "-"),
                        result = #date(Number.FromText(parts{2}), Number.FromText(parts{1}), Number.FromText(parts{0}))
                    in
                        result,
                type date
            }
        }
    )
