let
    // These must match the query names already loaded in Power BI.
    ProductMasterSource = #"Product Master",
    CohortSource = #"Cohort Schedule",
    IndexSource = #"Index Price",
    FXSource = #"FX Rate",

    CleanColumnName = (name as text) as text =>
        Text.Upper(
            Text.Remove(
                Text.Trim(Text.From(name)),
                {" ", ".", "_", "-", "(", ")", "/", "\", "#", ":", "'", """", Character.FromNumber(160)}
            )
        ),

    CleanText = (value as any) as nullable text =>
        if value = null then null else Text.Trim(Text.From(value)),

    CleanIndexCode = (value as any) as nullable text =>
        let
            cleaned = if value = null then null else CleanColumnName(Text.From(value)),
            withoutIndex = if cleaned <> null and Text.EndsWith(cleaned, "INDEX") then Text.Start(cleaned, Text.Length(cleaned) - 5) else cleaned
        in
            withoutIndex,

    ToNumber = (value as any) as nullable number =>
        let
            t = if value = null then null else Text.Trim(Text.From(value)),
            removed = if t = null then null else Text.Replace(Text.Replace(Text.Replace(t, "%", ""), ",", ""), "~", ""),
            n = try Number.From(value) otherwise try Number.FromText(removed) otherwise null
        in
            n,

    ToRate = (value as any) as nullable number =>
        let
            n = ToNumber(value)
        in
            if n = null then null else if n > 1 then n / 100 else n,

    ToDate = (value as any) as nullable date =>
        try Date.From(value)
        otherwise try Date.FromText(Text.From(value), "en-US")
        otherwise try Date.FromText(Text.From(value), "en-GB")
        otherwise null,

    NormalizeColumns = (tbl as table) as table =>
        Table.TransformColumnNames(tbl, each CleanColumnName(_)),

    AddMissingColumns = (tbl as table, required as list) as table =>
        List.Accumulate(
            required,
            tbl,
            (state as table, col as text) =>
                if Table.HasColumns(state, col) then state else Table.AddColumn(state, col, each null)
        ),

    ProductMasterRaw = NormalizeColumns(ProductMasterSource),
    ProductMasterColumns = AddMissingColumns(
        ProductMasterRaw,
        {"COMPANYNAME", "PRODUCTNAME", "INDEX", "INDEXCODE", "PR", "FORMULA", "PRINCIPAL", "FLOORRATE", "CAPRATE", "VOLATILITY"}
    ),
    ProductMasterSelected = Table.SelectColumns(
        ProductMasterColumns,
        {"COMPANYNAME", "PRODUCTNAME", "INDEX", "INDEXCODE", "PR", "FORMULA", "PRINCIPAL", "FLOORRATE", "CAPRATE", "VOLATILITY"}
    ),
    ProductMasterTyped = Table.TransformColumns(
        ProductMasterSelected,
        {
            {"COMPANYNAME", each CleanText(_), type text},
            {"PRODUCTNAME", each CleanText(_), type text},
            {"INDEX", each CleanText(_), type text},
            {"INDEXCODE", each CleanIndexCode(_), type text},
            {"PR", each ToRate(_), type number},
            {"FORMULA", each if _ = null or Text.Trim(Text.From(_)) = "" then "PR" else Text.Upper(Text.Replace(Text.Trim(Text.From(_)), " ", "_")), type text},
            {"PRINCIPAL", each ToNumber(_), type number},
            {"FLOORRATE", each ToRate(_), type number},
            {"CAPRATE", each ToRate(_), type number},
            {"VOLATILITY", each ToRate(_), type number}
        }
    ),
    ProductMasterDefaults = Table.TransformColumns(
        Table.AddColumn(
            Table.AddColumn(
                Table.AddColumn(
                    Table.AddColumn(
                        ProductMasterTyped,
                        "CompanyFinal",
                        each if [COMPANYNAME] = null or [COMPANYNAME] = "" then "MTL" else [COMPANYNAME],
                        type text
                    ),
                    "PrincipalFinal",
                    each if [PRINCIPAL] = null then 100 else [PRINCIPAL],
                    type number
                ),
                "CapRateFinal",
                each if [CAPRATE] = null then [PR] else [CAPRATE],
                type number
            ),
            "VolatilityFinal",
            each if [VOLATILITY] = null then if [CAPRATE] = null then [PR] else [CAPRATE] else [VOLATILITY],
            type number
        ),
        {{"FLOORRATE", each if _ = null then 0 else _, type number}}
    ),
    ProductMaster = Table.RenameColumns(
        Table.SelectColumns(
            ProductMasterDefaults,
            {"CompanyFinal", "PRODUCTNAME", "INDEX", "INDEXCODE", "PR", "FORMULA", "PrincipalFinal", "FLOORRATE", "CapRateFinal", "VolatilityFinal"}
        ),
        {
            {"CompanyFinal", "Company"},
            {"PRODUCTNAME", "ProductName"},
            {"INDEX", "IndexName"},
            {"INDEXCODE", "IndexCode"},
            {"FORMULA", "FormulaType"},
            {"PrincipalFinal", "Principal"},
            {"FLOORRATE", "FloorRate"},
            {"CapRateFinal", "CapRate"},
            {"VolatilityFinal", "Volatility"}
        }
    ),

    CohortRaw = NormalizeColumns(CohortSource),
    CohortColumns = AddMissingColumns(
        CohortRaw,
        {"PRODUCTNAME", "COHORTNO", "COHORTDURATION", "COHORTSTARTDATE", "COHORTENDDATE"}
    ),
    CohortSelected = Table.SelectColumns(
        CohortColumns,
        {"PRODUCTNAME", "COHORTNO", "COHORTDURATION", "COHORTSTARTDATE", "COHORTENDDATE"}
    ),
    CohortSchedule = Table.TransformColumns(
        CohortSelected,
        {
            {"PRODUCTNAME", each CleanText(_), type text},
            {"COHORTNO", each ToNumber(_), Int64.Type},
            {"COHORTDURATION", each ToNumber(_), type number},
            {"COHORTSTARTDATE", each ToDate(_), type date},
            {"COHORTENDDATE", each ToDate(_), type date}
        }
    ),

    IndexRaw = NormalizeColumns(IndexSource),
    IndexColumns = AddMissingColumns(IndexRaw, {"DATE"}),
    IndexTyped = Table.TransformColumns(IndexColumns, {{"DATE", each ToDate(_), type date}}),
    IndexPriceLong = Table.UnpivotOtherColumns(IndexTyped, {"DATE"}, "IndexCode", "Price"),
    IndexPriceTyped = Table.TransformColumns(
        IndexPriceLong,
        {
            {"IndexCode", each CleanIndexCode(_), type text},
            {"Price", each ToNumber(_), type number}
        }
    ),
    IndexPrice = Table.RenameColumns(
        Table.SelectRows(IndexPriceTyped, each [DATE] <> null and [IndexCode] <> null and [IndexCode] <> "" and [Price] <> null and [Price] <> 0),
        {{"DATE", "Date"}}
    ),

    FXRaw = NormalizeColumns(FXSource),
    FXColumns = AddMissingColumns(FXRaw, {"DATE", "MONTH", "เดือน", "USDTHB", "USDTH"}),
    FXDateColumn =
        if Table.HasColumns(FXColumns, "DATE") and List.NonNullCount(FXColumns[DATE]) > 0 then "DATE"
        else if Table.HasColumns(FXColumns, "MONTH") and List.NonNullCount(FXColumns[MONTH]) > 0 then "MONTH"
        else if Table.HasColumns(FXColumns, "เดือน") then "เดือน"
        else "DATE",
    FXRateColumn =
        if Table.HasColumns(FXColumns, "USDTHB") and List.NonNullCount(FXColumns[USDTHB]) > 0 then "USDTHB"
        else if Table.HasColumns(FXColumns, "USDTH") and List.NonNullCount(FXColumns[USDTH]) > 0 then "USDTH"
        else "USDTHB",
    FXSelected = Table.SelectColumns(FXColumns, {FXDateColumn, FXRateColumn}, MissingField.UseNull),
    FXRenamed = Table.RenameColumns(FXSelected, {{FXDateColumn, "Date"}, {FXRateColumn, "FXRate"}}, MissingField.Ignore),
    FXTyped = Table.TransformColumns(FXRenamed, {{"Date", each ToDate(_), type date}, {"FXRate", each ToNumber(_), type number}}),
    FXWithPair = Table.AddColumn(Table.SelectRows(FXTyped, each [Date] <> null), "FXPair", each "USD/THB", type text),

    MergeProduct = Table.NestedJoin(
        CohortSchedule,
        {"PRODUCTNAME"},
        ProductMaster,
        {"ProductName"},
        "Product",
        JoinKind.LeftOuter
    ),
    ExpandProduct = Table.ExpandTableColumn(
        MergeProduct,
        "Product",
        {"Company", "IndexName", "IndexCode", "PR", "FormulaType", "Principal", "FloorRate", "CapRate", "Volatility"},
        {"Company", "IndexName", "IndexCode", "PR", "FormulaType", "Principal", "FloorRate", "CapRate", "Volatility"}
    ),

    AddObservationEndDate = Table.AddColumn(
        ExpandProduct,
        "ObservationEndDate",
        each
            if [COHORTENDDATE] <> null then [COHORTENDDATE]
            else if [COHORTDURATION] <> null and [COHORTSTARTDATE] <> null then Date.AddMonths([COHORTSTARTDATE], Number.RoundDown([COHORTDURATION]))
            else if [COHORTSTARTDATE] <> null then Date.AddYears([COHORTSTARTDATE], 3)
            else null,
        type date
    ),

    MergeIndex = Table.NestedJoin(
        AddObservationEndDate,
        {"IndexCode"},
        IndexPrice,
        {"IndexCode"},
        "IndexPrice",
        JoinKind.LeftOuter
    ),
    ExpandIndex = Table.ExpandTableColumn(MergeIndex, "IndexPrice", {"Date", "Price"}, {"Date", "Price"}),
    FilterPeriod = Table.SelectRows(
        ExpandIndex,
        each [Date] <> null and [COHORTSTARTDATE] <> null and [Date] >= [COHORTSTARTDATE] and ([ObservationEndDate] = null or [Date] <= [ObservationEndDate])
    ),

    BaseValues = Table.Group(
        FilterPeriod,
        {"PRODUCTNAME", "COHORTNO"},
        {{"IndexBaseValue", each try Table.Sort(_, {{"Date", Order.Ascending}}){0}[Price] otherwise null, type number}}
    ),
    MergeBase = Table.NestedJoin(FilterPeriod, {"PRODUCTNAME", "COHORTNO"}, BaseValues, {"PRODUCTNAME", "COHORTNO"}, "Base", JoinKind.LeftOuter),
    ExpandBase = Table.ExpandTableColumn(MergeBase, "Base", {"IndexBaseValue"}, {"IndexBaseValue"}),

    MergeFX = Table.NestedJoin(ExpandBase, {"Date"}, FXWithPair, {"Date"}, "FX", JoinKind.LeftOuter),
    ExpandFX = Table.ExpandTableColumn(MergeFX, "FX", {"FXPair", "FXRate"}, {"FXPair", "FXRate"}),

    RenameColumns = Table.RenameColumns(
        ExpandFX,
        {
            {"PRODUCTNAME", "ProductName"},
            {"COHORTNO", "CohortNo"},
            {"COHORTSTARTDATE", "CohortStartDate"},
            {"COHORTENDDATE", "CohortEndDate"}
        },
        MissingField.Ignore
    ),
    WithCompanyName = Table.AddColumn(RenameColumns, "CompanyName", each [Company], type text),

    FinalColumns = Table.SelectColumns(
        WithCompanyName,
        {
            "Company",
            "CompanyName",
            "ProductName",
            "IndexName",
            "IndexCode",
            "PR",
            "FormulaType",
            "Principal",
            "FloorRate",
            "CapRate",
            "Volatility",
            "CohortNo",
            "CohortStartDate",
            "CohortEndDate",
            "ObservationEndDate",
            "IndexBaseValue",
            "Date",
            "Price",
            "FXPair",
            "FXRate"
        },
        MissingField.UseNull
    )
in
    FinalColumns
