let
    ProductMasterSource = #"Product Master",
    CohortSource = #"Cohort Schedule",
    IndexSource = #"Index Price",
    FXSource = #"FX Rate",

    ProductMaster = Table.TransformColumnTypes(
        ProductMasterSource,
        {
            {"Company Name", type text},
            {"Product Name", type text},
            {"Index", type text},
            {"Index Code", type text},
            {"PR", type number},
            {"FormulaType", type text},
            {"Principal", type number},
            {"FloorRate", type number},
            {"CapRate", type number}
        }
    ),

    CohortSchedule = Table.TransformColumnTypes(
        CohortSource,
        {
            {"Product Name", type text},
            {"Cohort No.", Int64.Type},
            {"Cohort Start Date", type date},
            {"Cohort End Date", type date},
            {"Index Base Value", type number}
        }
    ),

    IndexTyped = Table.TransformColumnTypes(
        IndexSource,
        {{"Date", type date}}
    ),

    IndexPriceLong = Table.UnpivotOtherColumns(
        IndexTyped,
        {"Date"},
        "IndexCode",
        "Price"
    ),

    IndexPriceTyped = Table.TransformColumnTypes(
        IndexPriceLong,
        {
            {"IndexCode", type text},
            {"Price", type number}
        }
    ),

    FXRenamed = Table.RenameColumns(
        FXSource,
        {
            {"เดือน", "Date"},
            {"USD/THB", "FXRate"}
        },
        MissingField.Ignore
    ),

    FXTyped = Table.TransformColumnTypes(
        FXRenamed,
        {
            {"Date", type date},
            {"FXRate", type number}
        }
    ),

    FXWithPair = Table.AddColumn(
        FXTyped,
        "FXPair",
        each "USD/THB",
        type text
    ),

    MergeProduct = Table.NestedJoin(
        CohortSchedule,
        {"Product Name"},
        ProductMaster,
        {"Product Name"},
        "Product",
        JoinKind.LeftOuter
    ),

    ExpandProduct = Table.ExpandTableColumn(
        MergeProduct,
        "Product",
        {
            "Company Name",
            "Index",
            "Index Code",
            "PR",
            "FormulaType",
            "Principal",
            "FloorRate",
            "CapRate"
        },
        {
            "Company",
            "IndexName",
            "IndexCode",
            "PR",
            "FormulaType",
            "Principal",
            "FloorRate",
            "CapRate"
        }
    ),

    MergeIndex = Table.NestedJoin(
        ExpandProduct,
        {"IndexCode"},
        IndexPriceTyped,
        {"IndexCode"},
        "IndexPrice",
        JoinKind.LeftOuter
    ),

    ExpandIndex = Table.ExpandTableColumn(
        MergeIndex,
        "IndexPrice",
        {"Date", "Price"},
        {"Date", "Price"}
    ),

    FilterAfterStart = Table.SelectRows(
        ExpandIndex,
        each [Date] >= [Cohort Start Date]
    ),

    AddObservationEndDate = Table.AddColumn(
        FilterAfterStart,
        "ObservationEndDate",
        each Date.AddYears([Cohort Start Date], 3),
        type date
    ),

    FilterBeforeObservationEnd = Table.SelectRows(
        AddObservationEndDate,
        each [Date] <= [ObservationEndDate]
    ),

    MergeFX = Table.NestedJoin(
        FilterBeforeObservationEnd,
        {"Date"},
        FXWithPair,
        {"Date"},
        "FX",
        JoinKind.LeftOuter
    ),

    ExpandFX = Table.ExpandTableColumn(
        MergeFX,
        "FX",
        {"FXPair", "FXRate"},
        {"FXPair", "FXRate"}
    ),

    RenameColumns = Table.RenameColumns(
        ExpandFX,
        {
            {"Product Name", "ProductName"},
            {"Cohort No.", "CohortNo"},
            {"Cohort Start Date", "CohortStartDate"},
            {"Cohort End Date", "CohortEndDate"},
            {"Index Base Value", "IndexBaseValue"}
        }
    ),

    FinalColumns = Table.SelectColumns(
        RenameColumns,
        {
            "Company",
            "ProductName",
            "IndexName",
            "IndexCode",
            "PR",
            "FormulaType",
            "Principal",
            "FloorRate",
            "CapRate",
            "CohortNo",
            "CohortStartDate",
            "CohortEndDate",
            "ObservationEndDate",
            "IndexBaseValue",
            "Date",
            "Price",
            "FXPair",
            "FXRate"
        }
    )
in
    FinalColumns
